invest:
  zhi-pu-ai:
    api-key: ${ZHI_PU_AI_API_KEY}
    model: glm-4.7-flash
server:
  servlet:
    context-path: /invest/macro/api
spring:
  application:
    name: invest-macro
  datasource:
    username: sa
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.163.com
    port: 25
    username: qazcxh@163.com
    password: ${QAZCXH_163_COM_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
  profiles:
    active: chixuehui
---
server:
  port: 6012
spring:
  config:
    activate:
      on-profile: chixuehui
    import:
      - file:${user.home}/IdeaProjects/ricewines/local-config/common-chixuehui.yml
      - file:${user.home}/IdeaProjects/ricewines/local-config/invest-macro-chixuehui.yml
---
spring:
  config:
    activate:
      on-profile: chixuehuidocker
    import:
      - file:/config/common-chixuehuidocker.yml
      - file:/config/invest-macro-chixuehuidocker.yml