// 根项目 build.gradle（Groovy DSL）
buildscript {
    repositories {
        mavenLocal()
        maven { url = 'https://maven.aliyun.com/repository/public/' }
        maven { url = 'https://maven.aliyun.com/repository/gradle-plugin' }
        gradlePluginPortal()
        mavenCentral()
    }
}

// 根项目不需要 java 插件
plugins {
    id 'maven-publish'
    id 'org.jreleaser' version '1.24.0'
    id 'signing'
}

// ########## 全局公共配置 ##########
allprojects {
    group = 'io.github.ricewines'
    version = '0.1.15'

    repositories {
        maven { url = 'https://maven.aliyun.com/repository/public/' }
        mavenLocal()
        mavenCentral()
    }
}

// ########## 只给子项目配置发布、签名、Java ##########
subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    compileJava {
        options.encoding = 'UTF-8'
    }

    compileTestJava {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }

        withSourcesJar()
        withJavadocJar()
    }

    javadoc {
        options.addBooleanOption('Xdoclint:none', true)
    }

    dependencies {
        implementation("org.springframework.boot:spring-boot-starter-freemarker")
        annotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }

    tasks.test {
        useJUnitPlatform()
    }
    jreleaser {
        signing {
            pgp {
                active = 'ALWAYS'
                armored = true
            }
        }
        deploy {
            maven {
                mavenCentral {
                    sonatype {
                        active = 'RELEASE'
                        url = 'https://central.sonatype.com/api/v1/publisher'
                        stagingRepository('target/staging-deploy')
                    }
                }
            }
        }
    }
}