plugins {
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}
dependencies {
    implementation 'ai.z.openapi:zai-sdk:0.3.4'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation "org.commonmark:commonmark"
    implementation "org.commonmark:commonmark-ext-gfm-strikethrough"
    implementation "org.commonmark:commonmark-ext-gfm-tables"

    implementation("cn.hutool:hutool-all:5.8.46")
    implementation("org.jsoup:jsoup:1.22.2")
    implementation("org.slf4j:slf4j-api")
    implementation("org.springframework.boot:spring-boot-starter-freemarker")
}
// SB3 对应的 Spring Cloud
dependencyManagement {
    imports {
        mavenBom "org.commonmark:commonmark-parent:0.28.0"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.0.2"
    }
}
// 强制所有 Jackson 使用 2.19.4
configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.fasterxml.jackson.core') {
            details.useVersion '2.19.4'
        }
    }
}