spring:
  application:
    name: accountings
  datasource:
    url: jdbc:h2:~/invest/ifrs_accounting;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: chixuehui
---
server:
  port: 5001
spring:
  config:
    activate:
      on-profile: chixuehui
    import:
      - file:${user.home}/IdeaProjects/ricewines/local-config/common-chixuehui.yml
---
spring:
  config:
    activate:
      on-profile: chixuehuidocker
    import:
      - file:/app/ricewines-deploy/chixuehuidocker/common-chixuehuidocker.yml