CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(128),
    type VARCHAR(32),
    ifrs_standard VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_no VARCHAR(64) UNIQUE,
    voucher_date DATE,
    description VARCHAR(255),
    status VARCHAR(32),
    ifrs_basis VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS voucher_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT,
    account_id BIGINT,
    debit DECIMAL(19, 4),
    credit DECIMAL(19, 4),
    remark VARCHAR(255),
    CONSTRAINT fk_voucher_entries_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers (id),
    CONSTRAINT fk_voucher_entries_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

MERGE INTO accounts (code, name, type, ifrs_standard) KEY (code) VALUES
('1001', '现金及现金等价物', '资产', 'IAS 1'),
('1002', '银行存款', '资产', 'IAS 1'),
('1003', '短期投资', '资产', 'IAS 32'),
('1101', '应收账款', '资产', 'IAS 1'),
('1102', '坏账准备', '资产', 'IAS 37'),
('1201', '存货', '资产', 'IAS 2'),
('1301', '预付款项', '资产', 'IAS 1'),
('1401', '其他应收款', '资产', 'IAS 1'),
('1501', '长期股权投资', '资产', 'IAS 27'),
('1601', '固定资产', '资产', 'IAS 16'),
('1602', '累计折旧', '资产', 'IAS 16'),
('1701', '无形资产', '资产', 'IAS 38'),
('1702', '累计摊销', '资产', 'IAS 38'),
('1801', '商誉', '资产', 'IFRS 3'),
('1901', '递延所得税资产', '资产', 'IAS 12'),
('2001', '短期借款', '负债', 'IAS 1'),
('2101', '应付账款', '负债', 'IAS 1'),
('2201', '应付职工薪酬', '负债', 'IAS 19'),
('2301', '应交税费', '负债', 'IAS 12'),
('2401', '预收款项', '负债', 'IAS 1'),
('2501', '其他应付款', '负债', 'IAS 1'),
('2601', '长期借款', '负债', 'IAS 1'),
('2701', '应付债券', '负债', 'IAS 32'),
('2801', '预计负债', '负债', 'IAS 37'),
('2901', '递延所得税负债', '负债', 'IAS 12'),
('2902', '租赁负债', '负债', 'IFRS 16'),
('3001', '实收资本', '权益', 'IAS 1'),
('3101', '资本公积', '权益', 'IAS 1'),
('3201', '其他综合收益', '权益', 'IAS 1'),
('3301', '盈余公积', '权益', 'IAS 1'),
('3401', '未分配利润', '权益', 'IAS 1'),
('4001', '主营业务收入', '收入', 'IFRS 15'),
('4101', '其他业务收入', '收入', 'IAS 1'),
('4201', '投资收益', '收入', 'IAS 18'),
('4301', '公允价值变动收益', '收入', 'IFRS 9'),
('4401', '营业外收入', '收入', 'IAS 1'),
('5001', '主营业务成本', '费用', 'IAS 1'),
('5101', '其他业务成本', '费用', 'IAS 1'),
('5201', '销售费用', '费用', 'IAS 1'),
('5301', '管理费用', '费用', 'IAS 1'),
('5401', '财务费用', '费用', 'IAS 1'),
('5501', '资产减值损失', '费用', 'IAS 36'),
('5601', '所得税费用', '费用', 'IAS 12'),
('5701', '营业外支出', '费用', 'IAS 1');