# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 25
          # Java distribution. See the list of supported distributions in README file
          distribution: oracle
          # ID of the distributionManagement repository in the pom.xml file. Default is `github`
          server-id: central
          # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
          # Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".
          cache: gradle
      - name: Publish Central
        run: gradle clean publish
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}